name: Attic

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Attic
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.chvp.be
          cache: chvp
          token: '${{ secrets.ATTIC_AUTH_TOKEN }}'
          skip-push: true
      - run: nix build -L --no-link .#tetris
      - run: nix build -L --no-link .#devShells.x86_64-linux.default
      - run: nix eval --json ".#tetris.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
      - run: nix eval --json ".#devShells.x86_64-linux.default.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
