name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: chvp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#tetris
      - run: nix build -L --no-link .#devShells.x86_64-linux.default
      - run: nix eval --json ".#tetris.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - run: nix eval --json ".#devShells.x86_64-linux.default.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
