name: Update


on:
  schedule:
    - cron: '28 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: chvp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "(-source$|*.tgz|-modules-)"
      - run: nix flake update
      - run: nix build -L --no-link .#tetris
      - uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: "Update nixpkgs"
