name: Update


on:
  schedule:
    - cron: '28 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: chvp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#tetris
      - run: nix build -L --no-link .#devShells.x86_64-linux.default
      - run: nix eval --json ".#tetris.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - run: nix eval --json ".#devShells.x86_64-linux.default.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Update nixpkgs"
